name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Strip out the URL prefix in case the user inputs the full URL
          CLEANED_PATH=$(echo "${{ secrets.HF_SPACE_PATH }}" | sed 's|https://huggingface.co/spaces/||g' | sed 's|^/||g')
          git push --force https://x-access-token:$HF_TOKEN@huggingface.co/spaces/$CLEANED_PATH main:main
